#ifndef _MAIN_
#define _MAIN_




#include "stm32f4xx.h"
#include "stm32f411xe.h"



__STATIC_INLINE void MCU_Clock_Setup(void){
  
 

	RCC -> CR |= RCC_CR_HSEON;
	while(!(RCC -> CR & RCC_CR_HSERDY)){}
	RCC -> APB1ENR |= RCC_APB1ENR_PWREN;
	PWR ->CR |= PWR_CR_VOS;
	FLASH -> ACR |= FLASH_ACR_ICEN | FLASH_ACR_PRFTEN | FLASH_ACR_DCEN |
			FLASH_ACR_LATENCY_3WS;
	RCC -> CR |= RCC_CR_PLLON;
	RCC -> CFGR |= RCC_CFGR_HPRE_DIV1;
	RCC -> CFGR |= RCC_CFGR_PPRE1_DIV2;
	RCC -> CFGR |= RCC_CFGR_PPRE2_DIV1;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLM_4 | RCC_PLLCFGR_PLLM_3 | RCC_PLLCFGR_PLLM_0;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLN_7 | RCC_PLLCFGR_PLLN_6;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLP_1;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLQ_2;
	RCC -> CR |= RCC_CR_PLLI2SON;
	while(!(RCC->CR & RCC_CR_PLLI2SRDY)){}
	RCC -> CFGR |= RCC_CFGR_SW_PLL;
	while((RCC -> CFGR & RCC_CFGR_SWS_PLL) != RCC_CFGR_SWS_PLL);

 
  
}




__STATIC_INLINE void I2S_Clock_Setup(void)
{
	RCC -> PLLI2SCFGR |= RCC_PLLI2SCFGR_PLLI2SM_4;
	RCC -> PLLI2SCFGR |= RCC_PLLI2SCFGR_PLLI2SN_7 | RCC_PLLI2SCFGR_PLLI2SN_6;
	RCC -> PLLI2SCFGR |= RCC_PLLI2SCFGR_PLLI2SR_2 | RCC_PLLI2SCFGR_PLLI2SR_0;
	RCC -> CFGR &= ~RCC_CFGR_I2SSRC;
}










#endif

