#include "I2S.h"


void I2S1_Master__Init(void)
{
		//CLOCK CONFIGURATION
		RCC -> CR |= RCC_CR_PLLI2SON;
		RCC -> PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
		RCC -> PLLI2SCFGR |= (192 << 6) | (5 << 28) ;
		RCC -> APB2ENR |= RCC_APB2ENR_SPI1EN ;
		RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
		
		//PIN CONFIGURATION
		GPIOA -> MODER &= ~((GPIO_MODER_MODE4_0 | GPIO_MODER_MODE4_1) |
												(GPIO_MODER_MODE5_0 | GPIO_MODER_MODE5_1) |
												(GPIO_MODER_MODE7_0 | GPIO_MODER_MODE7_1));
		GPIOA -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED4_0 | GPIO_OSPEEDR_OSPEED4_1) |
												(GPIO_OSPEEDR_OSPEED5_0 | GPIO_OSPEEDR_OSPEED5_1) |
												(GPIO_OSPEEDR_OSPEED7_0 | GPIO_OSPEEDR_OSPEED7_1));	
		GPIOA -> PUPDR &= ~((GPIO_PUPDR_PUPDR4_0 | GPIO_PUPDR_PUPDR4_1) |
												(GPIO_PUPDR_PUPDR5_0 | GPIO_PUPDR_PUPDR5_1) |
												(GPIO_PUPDR_PUPDR7_0 | GPIO_PUPDR_PUPDR7_1));	
		GPIOA -> OTYPER |= GPIO_OTYPER_OT4 | GPIO_OTYPER_OT5 | GPIO_OTYPER_OT7;
		GPIOA->AFR[0] |= (5 << 16) | (5 << 20) | (5 << 28);
		
		//PERIPHERAL CONFIGURATION
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SMOD;  //I2S MODE 
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_1; //MASTER TRANSMIT
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_0 | SPI_I2SCFGR_I2SCFG_1 ; //MASTER RECEIVE
		SPI1 ->I2SCFGR &= ~SPI_I2SCFGR_I2SSTD;  //I2S PHILLIPS STANDARD
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_DATLEN_0; //24BIT DATA LENGTH
		SPI1 -> I2SPR |= (1<< 1 | 12);
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SE;  //I2S ENABLED

}
//


void I2S2_Master_Init(void)
{
 //CLOCK CONFIGURATION
  RCC -> CR |= RCC_CR_PLLI2SON;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
	RCC -> PLLI2SCFGR |= (192 << 6) | (5 << 28) ;
	
	RCC -> APB2ENR |= RCC_APB1ENR_SPI2EN ;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	//PIN CONFIGURATION
	GPIOB -> MODER &= ~((GPIO_MODER_MODE10_0 | GPIO_MODER_MODE10_1) |
	                    (GPIO_MODER_MODE12_0 | GPIO_MODER_MODE12_1) |
	                    (GPIO_MODER_MODE15_0 | GPIO_MODER_MODE15_1));
	GPIOB -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED10_0 | GPIO_OSPEEDR_OSPEED10_1) |
	                    (GPIO_OSPEEDR_OSPEED12_0 | GPIO_OSPEEDR_OSPEED12_1) |
	                    (GPIO_OSPEEDR_OSPEED15_0 | GPIO_OSPEEDR_OSPEED15_1));	
	GPIOB -> PUPDR &= ~((GPIO_PUPDR_PUPDR10_0 | GPIO_PUPDR_PUPDR10_1) |
	                    (GPIO_PUPDR_PUPDR12_0 | GPIO_PUPDR_PUPDR12_1) |
	                    (GPIO_PUPDR_PUPDR15_0 | GPIO_PUPDR_PUPDR15_1));	
  GPIOB -> OTYPER |= GPIO_OTYPER_OT10 | GPIO_OTYPER_OT12 | GPIO_OTYPER_OT15;
	GPIOB->AFR[1] |= (5 << 8) | (5 << 16) | (5 << 28);
	
	//PERIPHERAL CONFIGURATION
	SPI2 ->I2SCFGR |= SPI_I2SCFGR_I2SMOD;  //I2S MODE 
	SPI2 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_1; //MASTER TRANSMIT
	SPI2 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_0 | SPI_I2SCFGR_I2SCFG_1 ; //MASTER RECEIVE
	SPI2 ->I2SCFGR &= ~SPI_I2SCFGR_I2SSTD;  //I2S PHILLIPS STANDARD
	SPI2 ->I2SCFGR |= SPI_I2SCFGR_DATLEN_0; //24BIT DATA LENGTH
	SPI2 -> I2SPR |= (1<< 1 | 12);
	SPI2 ->I2SCFGR |= SPI_I2SCFGR_I2SE;  //I2S ENABLED	
}
//

void I2S3_Master__Init(void)
{
  //CLOCK CONFIGURATION
  RCC -> CR |= RCC_CR_PLLI2SON;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
	RCC -> PLLI2SCFGR |= (192 << 6) | (5 << 28) ;
	
	RCC -> APB2ENR |= RCC_APB1ENR_SPI3EN ;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN;

	//PIN CONFIGURATION
	GPIOB -> MODER &= ~((GPIO_MODER_MODE9_0 | GPIO_MODER_MODE9_1) |
	                    (GPIO_MODER_MODE5_0 | GPIO_MODER_MODE5_1) );
	GPIOB -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED9_0 | GPIO_OSPEEDR_OSPEED9_1) |
	                    (GPIO_OSPEEDR_OSPEED5_0 | GPIO_OSPEEDR_OSPEED5_1));	
	GPIOB -> PUPDR &= ~((GPIO_PUPDR_PUPDR9_0 | GPIO_PUPDR_PUPDR9_1) |
	                    (GPIO_PUPDR_PUPDR5_0 | GPIO_PUPDR_PUPDR5_1));	
  GPIOB -> OTYPER |= GPIO_OTYPER_OT9 | GPIO_OTYPER_OT5 ;
	GPIOB->AFR[1] |= (5 << 8) | (5 << 16) | (5 << 28);
	
	GPIOA -> MODER &= ~((GPIO_MODER_MODE15_0 | GPIO_MODER_MODE15_1));
	GPIOA -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED15_0 | GPIO_OSPEEDR_OSPEED15_1));	
	GPIOA -> PUPDR &= ~((GPIO_PUPDR_PUPDR15_0 | GPIO_PUPDR_PUPDR15_1));	
  GPIOA -> OTYPER |= GPIO_OTYPER_OT15 ;
	GPIOA->AFR[1] |= (5 << 28);
	
	//PERIPHERAL CONFIGURATION
	SPI3 ->I2SCFGR |= SPI_I2SCFGR_I2SMOD;  //I2S MODE 
	SPI3 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_1; //MASTER TRANSMIT
	SPI3 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_0 | SPI_I2SCFGR_I2SCFG_1 ; //MASTER RECEIVE
	SPI3 ->I2SCFGR &= ~SPI_I2SCFGR_I2SSTD;  //I2S PHILLIPS STANDARD
	SPI3 ->I2SCFGR |= SPI_I2SCFGR_DATLEN_0; //24BIT DATA LENGTH
	SPI3 -> I2SPR |= (1<< 1 | 12);
	SPI3 ->I2SCFGR |= SPI_I2SCFGR_I2SE;  //I2S ENABLED
}
//


void I2S4_Master_Init(void)
{
  //CLOCK CONFIGURATION
  RCC -> CR |= RCC_CR_PLLI2SON;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
	RCC -> PLLI2SCFGR |= (192 << 6) | (5 << 28) ;
	
	RCC -> APB2ENR |= RCC_APB1ENR_SPI3EN ;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN;

	//PIN CONFIGURATION
	GPIOB -> MODER &= ~((GPIO_MODER_MODE13_0 | GPIO_MODER_MODE13_1) |
	                    (GPIO_MODER_MODE12_0 | GPIO_MODER_MODE12_1) );
	GPIOB -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED12_0 | GPIO_OSPEEDR_OSPEED12_1) |
	                    (GPIO_OSPEEDR_OSPEED13_0 | GPIO_OSPEEDR_OSPEED13_1));	
	GPIOB -> PUPDR &= ~((GPIO_PUPDR_PUPDR12_0 | GPIO_PUPDR_PUPDR12_1) |
	                    (GPIO_PUPDR_PUPDR13_0 | GPIO_PUPDR_PUPDR13_1));	
  GPIOB -> OTYPER |= GPIO_OTYPER_OT12 | GPIO_OTYPER_OT13 ;
	GPIOB->AFR[1] |= (6 << 20) | (6 << 16) ;
	
	GPIOA -> MODER &= ~((GPIO_MODER_MODE1_0 | GPIO_MODER_MODE1_1));
	GPIOA -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED1_0 | GPIO_OSPEEDR_OSPEED1_1));	
	GPIOA -> PUPDR &= ~((GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR1_1));	
  GPIOA -> OTYPER |= GPIO_OTYPER_OT1 ;
	GPIOA->AFR[0] |= (6 << 4);
	
	//PERIPHERAL CONFIGURATION
	SPI4 ->I2SCFGR |= SPI_I2SCFGR_I2SMOD;  //I2S MODE 
	SPI4 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_1; //MASTER TRANSMIT
	SPI4 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_0 | SPI_I2SCFGR_I2SCFG_1 ; //MASTER RECEIVE
	SPI4 ->I2SCFGR &= ~SPI_I2SCFGR_I2SSTD;  //I2S PHILLIPS STANDARD
	SPI4 ->I2SCFGR |= SPI_I2SCFGR_DATLEN_0; //24BIT DATA LENGTH
	SPI4 -> I2SPR |= (1<< 1 | 12);
	SPI4 ->I2SCFGR |= SPI_I2SCFGR_I2SE;  //I2S ENABLED
}
//

void I2S5_Master_Init(void)
{
  //CLOCK CONFIGURATION
  RCC -> CR |= RCC_CR_PLLI2SON;
	RCC -> PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
	RCC -> PLLI2SCFGR |= (192 << 6) | (5 << 28) ;
	
	RCC -> APB2ENR |= RCC_APB1ENR_SPI3EN ;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN;

	//PIN CONFIGURATION
	GPIOB -> MODER &= ~((GPIO_MODER_MODE0_0 | GPIO_MODER_MODE0_1) |
	                    (GPIO_MODER_MODE1_0 | GPIO_MODER_MODE1_1) );
	GPIOB -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED0_0 | GPIO_OSPEEDR_OSPEED0_1) |
	                    (GPIO_OSPEEDR_OSPEED11_0 | GPIO_OSPEEDR_OSPEED1_1));	
	GPIOB -> PUPDR &= ~((GPIO_PUPDR_PUPDR0_0 | GPIO_PUPDR_PUPDR0_1) |
	                    (GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR1_1));	
  GPIOB -> OTYPER |= GPIO_OTYPER_OT0 | GPIO_OTYPER_OT1 ;
	GPIOB->AFR[1] |= (6 << 0) | (6 << 4) ;
	
	GPIOA -> MODER &= ~((GPIO_MODER_MODE10_0 | GPIO_MODER_MODE10_1));
	GPIOA -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED10_0 | GPIO_OSPEEDR_OSPEED10_1));	
	GPIOA -> PUPDR &= ~((GPIO_PUPDR_PUPDR10_0 | GPIO_PUPDR_PUPDR10_1));	
  GPIOA -> OTYPER |= GPIO_OTYPER_OT10 ;
	GPIOA->AFR[0] |= (6 << 8);
	
	//PERIPHERAL CONFIGURATION
	SPI5 ->I2SCFGR |= SPI_I2SCFGR_I2SMOD;  //I2S MODE 
	SPI5 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_1; //MASTER TRANSMIT
	SPI5 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_0 | SPI_I2SCFGR_I2SCFG_1 ; //MASTER RECEIVE
	SPI5 ->I2SCFGR &= ~SPI_I2SCFGR_I2SSTD;  //I2S PHILLIPS STANDARD
	SPI5 ->I2SCFGR |= SPI_I2SCFGR_DATLEN_0; //24BIT DATA LENGTH
	SPI5 -> I2SPR |= (1<< 1 | 12);
	SPI5 ->I2SCFGR |= SPI_I2SCFGR_I2SE;  //I2S ENABLED
}
//

void I2S_Master_Send_Data(SPI_TypeDef *I2S, uint32_t *r_channel,  uint32_t *l_channel, int length )
{

	int i = 0;
	
	if(I2S == SPI1)
	{
	GPIOA->BSRR |= GPIO_BSRR_BS4;
	}
	else if(I2S == SPI2)
	{
	GPIOB->BSRR |= GPIO_BSRR_BS9;
	}
	else if(I2S == SPI3)
	{
	GPIOA->BSRR |= GPIO_BSRR_BS15;
	}
	else if(I2S == SPI4)
	{
        GPIOB->BSRR |= GPIO_BSRR_BS12;
	}
	else if(I2S == SPI5)
	{
	GPIOB->BSRR |= GPIO_BSRR_BS1;
	}
				
	for(i = 0; i < length; i++)
	{
	if(!(I2S -> SR & SPI_SR_CHSIDE))
	{
						
	I2S -> DR = (0x0000FFFF & l_channel[i]);
	while(!(I2S -> SR & SPI_SR_TXE));
	I2S -> DR = (0xFFFF0000 & l_channel[i]);
	while(!(I2S -> SR & SPI_SR_TXE));
	}
						
	if((I2S -> SR & SPI_SR_CHSIDE))
	{
	I2S -> DR = (0x0000FFFF & r_channel[i]);
	while(!(I2S -> SR & SPI_SR_TXE));
	I2S -> DR = (0xFFFF0000 & r_channel[i]);
	while(!(I2S -> SR & SPI_SR_TXE));
	}
					
	}
					
					
					
}
//	
