#include "I2S.h"


void I2S1_Master__Init(void)
{
		//CLOCK CONFIGURATION
		RCC -> CR |= RCC_CR_PLLI2SON;
		RCC -> PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSE;
		RCC -> PLLI2SCFGR |= (192 << 6) | (5 << 28) ;
		RCC -> APB2ENR |= RCC_APB2ENR_SPI1EN ;
		RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
		
		//PIN CONFIGURATION
		GPIOA -> MODER &= ~((GPIO_MODER_MODE4_0 | GPIO_MODER_MODE4_1) |
												(GPIO_MODER_MODE5_0 | GPIO_MODER_MODE5_1) |
												(GPIO_MODER_MODE7_0 | GPIO_MODER_MODE7_1));
		GPIOA -> OSPEEDR |= ((GPIO_OSPEEDR_OSPEED4_0 | GPIO_OSPEEDR_OSPEED4_1) |
												(GPIO_OSPEEDR_OSPEED5_0 | GPIO_OSPEEDR_OSPEED5_1) |
												(GPIO_OSPEEDR_OSPEED7_0 | GPIO_OSPEEDR_OSPEED7_1));	
		GPIOA -> PUPDR &= ~((GPIO_PUPDR_PUPDR4_0 | GPIO_PUPDR_PUPDR4_1) |
												(GPIO_PUPDR_PUPDR5_0 | GPIO_PUPDR_PUPDR5_1) |
												(GPIO_PUPDR_PUPDR7_0 | GPIO_PUPDR_PUPDR7_1));	
		GPIOA -> OTYPER |= GPIO_OTYPER_OT4 | GPIO_OTYPER_OT5 | GPIO_OTYPER_OT7;
		GPIOA->AFR[0] |= (5 << 16) | (5 << 20) | (5 << 28);
		
		//PERIPHERAL CONFIGURATION
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SMOD;  //I2S MODE 
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_1; //MASTER TRANSMIT
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SCFG_0 | SPI_I2SCFGR_I2SCFG_1 ; //MASTER RECEIVE
		SPI1 ->I2SCFGR &= ~SPI_I2SCFGR_I2SSTD;  //I2S PHILLIPS STANDARD
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_DATLEN_0; //24BIT DATA LENGTH
		SPI1 -> I2SPR |= (1<< 1 | 12);
		SPI1 ->I2SCFGR |= SPI_I2SCFGR_I2SE;  //I2S ENABLED

}
//

