/*
 * GPIO.h
 *
 *  Created on: 10-Sep-2021
 *      Author: Kunal
 */

#ifndef GPIO_GPIO_H_
#define GPIO_GPIO_H_

#include "main.h"

//GENERAL PURPPOSE OUTPUT
#define GENERAL_PURPOSE_OUTPUT_PUSHPULL		    0x2C
#define GENERAL_PURPOSE_OUTPUT_PUSHPULL_PULLUP	0x2D
#define GENERAL_PURPOSE_OUTPUT_PUSHPULL_PULLDW	0x2E
#define GENERAL_PURPOSE_OUTPUT_OPENDRAIN		0x3C
#define GENERAL_PURPOSE_OUTPUT_OPENDRAIN_PULLUP	0x3D
#define GENERAL_PURPOSE_OUTPUT_OPENDRAIN_PULLDW	0x3E

//ALTERNATE FUNCTION OUTPUT
#define ALTERNATE_FUNCTION_OUTPUT_PUSHPULL		    0x4C
#define ALTERNATE_FUNCTION_OUTPUT_PUSHPULL_PULLUP	0x4D
#define ALTERNATE_FUNCTION_OUTPUT_PUSHPULL_PULLDW	0x4E
#define ALTERNATE_FUNCTION_OUTPUT_OPENDRAIN		    0x5C
#define ALTERNATE_FUNCTION_OUTPUT_OPENDRAIN_PULLUP	0x5D
#define ALTERNATE_FUNCTION_OUTPUT_OPENDRAIN_PULLDW	0x5E

//GENERAL PURPPOSE INTPUT
#define INPUT_FLOATING	0x00
#define INPUT_PULLUP	0x01
#define INPUT_PULLDW	0x02

//ANALOG INPUT
#define ANALOG_INPUT	0x60

void GPIO_Pin_Setup(char Port, uint8_t pin, uint8_t function, uint8_t alternate_function);

#endif /* GPIO_GPIO_H_ */
